"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { readCart, writeCart } from "@/app/components/add-to-cart";

export default function CartClient() {
  const searchParams = useSearchParams();
  const companyId = searchParams.get("company");
  const [items, setItems] = useState(readCart()); const [discountCode, setDiscountCode] = useState(""); const [paymentMethod, setPaymentMethod] = useState<"stripe" | "invoice">("stripe"); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { const refresh = () => setItems(readCart()); window.addEventListener("kompetensportalen-cart-change", refresh); return () => window.removeEventListener("kompetensportalen-cart-change", refresh); }, []);
  function update(slug: string, quantity: number) { const next = items.map((item) => item.courseSlug === slug ? { ...item, quantity: Math.max(1, Math.min(10000, quantity)) } : item); setItems(next); writeCart(next); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setMessage(""); const response = await fetch("/api/orders/cart", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ items: items.map((item) => ({ courseSlug: item.courseSlug, quantity: item.quantity })), companyId: companyId || undefined, paymentMethod, discountCode: discountCode || undefined }) }); const data = await response.json() as { error?: string; payment?: { url?: string; approvalRequired?: boolean; configurationRequired?: boolean }; totals?: { totalSek: number } }; if (response.status === 401) setMessage("Logga in med ChatGPT för att fortsätta."); else if (!response.ok) setMessage(data.error ?? "Ordern kunde inte skapas."); else if (data.payment?.url) window.location.href = data.payment.url; else if (data.payment?.approvalRequired) setMessage(`Fakturaförfrågan skapad. Ordervärde: ${data.totals?.totalSek ?? 0} kr.`); else setMessage(`Ordern är skapad. Stripe behöver konfigureras. Ordervärde: ${data.totals?.totalSek ?? 0} kr.`); setLoading(false); }
  return <section className="section cart-section"><div className="cart-list">{items.length ? items.map((item) => <div className="cart-row" key={item.courseSlug}><div><strong>{item.name}</strong><span>{item.courseSlug}</span></div><label>Antal<input type="number" min="1" max="10000" value={item.quantity} onChange={(event) => update(item.courseSlug, Number(event.target.value))} /></label><button className="button button-light" type="button" onClick={() => { const next = items.filter((entry) => entry.courseSlug !== item.courseSlug); setItems(next); writeCart(next); }}>Ta bort</button></div>) : <div className="account-empty"><h2>Varukorgen är tom.</h2><p>Välj utbildningar från kurskatalogen.</p><Link className="button button-dark" href="/utbildningar">Till utbildningar <span>→</span></Link></div>}</div>{items.length > 0 && <form className="cart-checkout" onSubmit={submit}><p className="eyebrow">{companyId ? "Företagscheckout" : "Checkout"}</p><h2>Slutför köpet</h2>{companyId && <label>Betalsätt<select value={paymentMethod} onChange={(event) => setPaymentMethod(event.target.value as "stripe" | "invoice")}><option value="stripe">Kort / Apple Pay / Google Pay</option><option value="invoice">Faktura</option></select></label>}<label>Rabattkod <span>valfritt</span><input value={discountCode} onChange={(event) => setDiscountCode(event.target.value)} placeholder="SOMMAR20" /></label><button className="button button-dark" type="submit" disabled={loading}>{loading ? "Skapar order..." : paymentMethod === "invoice" ? "Skicka fakturaförfrågan →" : "Fortsätt till betalning →"}</button>{message && <p className="checkout-message" role="status">{message}</p>}</form>}</section>;
}
