"use client";

import { useState } from "react";
import { normalizeOdooCsvBundle } from "@/lib/odoo-csv";

const example = JSON.stringify({ course: { name: "Arbete på väg - APV 1.1-1.3" }, version: { version: "2.0" }, chapters: [{ title: "Kapitel 1", lessons: [{ title: "Introduktion", type: "article", body: { text: "Text från exporten." } }] }], questions: [], governingDocuments: [] }, null, 2);

export function OdooImportForm() {
  const [payload, setPayload] = useState(example);
  const [message, setMessage] = useState("");
  const [assetKey, setAssetKey] = useState("");
  const [assetFile, setAssetFile] = useState<File | null>(null);
  const [assetMessage, setAssetMessage] = useState("");
  const [csvFiles, setCsvFiles] = useState<File[]>([]);
  const [csvMessage, setCsvMessage] = useState("");
  const [report, setReport] = useState<{ importedChapters: number; importedLessons: number; importedQuestions: number; importedAnswers: number; importedQuizzes: number; importedQuizQuestions: number; importedGoverningDocuments: number; importedExamConfig: boolean; skippedExistingVersion: boolean; missingImages: string[]; missingVideos: string[]; warnings: string[]; errors: string[] } | null>(null);
  async function submit(event: React.FormEvent) { event.preventDefault(); setMessage(""); setReport(null); try { const response = await fetch("/api/import/odoo", { method: "POST", headers: { "content-type": "application/json" }, body: payload }); const data = await response.json() as { report?: typeof report; error?: string }; if (!response.ok || !data.report) return setMessage(data.error ?? "Importen misslyckades."); setReport(data.report); setMessage("Importen är klar. Kontrollera rapporten innan publicering."); } catch { setMessage("JSON-formatet kunde inte läsas."); } }
  async function uploadAsset(event: React.FormEvent) { event.preventDefault(); setAssetMessage(""); if (!assetFile || !assetKey.trim()) return setAssetMessage("Välj fil och ange en Storage-sökväg."); const form = new FormData(); form.set("file", assetFile); form.set("key", assetKey.trim()); const response = await fetch("/api/admin/course-assets", { method: "POST", body: form }); const data = await response.json() as { assetRef?: string; error?: string }; setAssetMessage(response.ok ? `Uppladdad: ${data.assetRef}` : (data.error ?? "Asseten kunde inte laddas upp.")); }
  async function importCsvBundle(event: React.FormEvent) { event.preventDefault(); setCsvMessage(""); if (!csvFiles.length) return setCsvMessage("Välj CSV-filer från exporten."); try { const files = Object.fromEntries(await Promise.all(csvFiles.map(async (file) => [file.name, await file.text()]))); const normalized = normalizeOdooCsvBundle(files); setPayload(JSON.stringify(normalized, null, 2)); setCsvMessage("CSV-bundlen är normaliserad. Kontrollera JSON och importera som utkast."); } catch (error) { setCsvMessage(error instanceof Error ? error.message : "CSV-bundlen kunde inte läsas."); } }
  return <section className="section course-admin-section"><form className="admin-form migration-form" onSubmit={submit}><p className="eyebrow">Normaliserad export</p><h2>Importera kursmaterial</h2><label>JSON från Odoo-exporten<textarea className="json-editor migration-editor" value={payload} onChange={(event) => setPayload(event.target.value)} /></label><button className="button button-dark" type="submit">Validera och importera som utkast →</button>{message && <p className="admin-message" role="status">{message}</p>}</form><form className="admin-form migration-form" onSubmit={importCsvBundle}><p className="eyebrow">CSV-bundle</p><h2>Konvertera Odoo-export</h2><label>CSV-filer<input type="file" accept=".csv,text/csv" multiple onChange={(event) => setCsvFiles(Array.from(event.target.files ?? []))} /></label><small>Välj course.csv, version.csv, chapters.csv, lessons.csv, questions.csv, answers.csv och eventuellt governing_documents.csv.</small><button className="button button-light" type="submit">Normalisera CSV →</button>{csvMessage && <p className="admin-message" role="status">{csvMessage}</p>}</form><form className="admin-form migration-form" onSubmit={uploadAsset}><p className="eyebrow">Kursassets</p><h2>Ladda upp bild, video eller PDF</h2><label>Storage-sökväg<input required value={assetKey} onChange={(event) => setAssetKey(event.target.value)} placeholder="apv/kapitel-1/intro.mp4" /></label><label>Fil<input required type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,application/pdf" onChange={(event) => setAssetFile(event.target.files?.[0] ?? null)} /></label><button className="button button-light" type="submit">Ladda upp asset</button>{assetMessage && <p className="admin-message" role="status">{assetMessage}</p>}</form>{report && <div className="admin-form migration-report"><p className="eyebrow">Migrationsrapport</p><h2>{report.skippedExistingVersion ? "Befintlig version lämnades orörd." : "Importen skapade en ny utkastsversion."}</h2><p>{report.importedChapters} kapitel · {report.importedLessons} lektioner · {report.importedQuestions} frågor · {report.importedAnswers} svar</p><p>{report.importedQuizzes} quiz · {report.importedQuizQuestions} quizfrågor · {report.importedGoverningDocuments} styrande dokument · slutprov {report.importedExamConfig ? "importerat" : "saknas"}</p>{report.warnings.length > 0 && <div><strong>Varningar</strong><ul>{report.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></div>}{report.errors.length > 0 && <div><strong>Fel</strong><ul>{report.errors.map((error) => <li key={error}>{error}</li>)}</ul></div>}{report.missingImages.length > 0 && <p>Saknade bilder: {report.missingImages.join(", ")}</p>}{report.missingVideos.length > 0 && <p>Saknade videor: {report.missingVideos.join(", ")}</p>}</div>}</section>;
}
