"use client";

import { useState } from "react";

type License = { id: string; courseId: string; courseName: string; createdAt: string };
type Recipient = { id: string; email: string };

export default function LicenseManager({ companyId, initialLicenses, initialRecipients }: { companyId: string; initialLicenses: License[]; initialRecipients: Recipient[] }) {
  const [licenses, setLicenses] = useState(initialLicenses);
  const [recipients] = useState(initialRecipients);
  const [recipientMode, setRecipientMode] = useState<"existing" | "email">(initialRecipients.length ? "existing" : "email");
  const [userId, setUserId] = useState(initialRecipients[0]?.id ?? "");
  const [email, setEmail] = useState("");
  const [selected, setSelected] = useState(initialLicenses[0]?.id ?? "");
  const [message, setMessage] = useState("");
  const [csv, setCsv] = useState("");
  async function assign(event: React.FormEvent) { event.preventDefault(); setMessage(""); const response = await fetch("/api/company/licenses/assign", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ licenseId: selected, userId: recipientMode === "existing" ? userId : undefined, email: recipientMode === "email" ? email : undefined }) }); const data = await response.json() as { error?: string }; if (!response.ok) return setMessage(data.error ?? "Platsen kunde inte tilldelas."); const remaining = licenses.filter((license) => license.id !== selected); setLicenses(remaining); setSelected(remaining[0]?.id ?? ""); setEmail(""); setMessage("Utbildningen tilldelades. Deltagaren får instruktioner via e-post."); }
  async function importCsv(event: React.FormEvent) { event.preventDefault(); setMessage(""); const license = licenses.find((item) => item.id === selected); if (!license) return setMessage("Välj en ledig utbildning först."); const response = await fetch("/api/company/licenses/assign", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyId, courseId: license.courseId, csv }) }); const data = await response.json() as { assigned?: { email: string }[]; failed?: { email: string; error: string }[]; error?: string }; if (!response.ok) return setMessage(data.error ?? "Importen kunde inte genomföras."); setCsv(""); setMessage(`${data.assigned?.length ?? 0} deltagare tilldelades. ${data.failed?.length ?? 0} rader kunde inte tilldelas.`); window.location.reload(); }
  return <section className="section license-manager"><div className="section-heading"><div><p className="eyebrow">Lediga licenser</p><h2>{licenses.length} platser kvar</h2></div><a className="button button-light" href="/api/company/report">Ladda ner CSV <span>↓</span></a></div>{licenses.length ? <><form className="license-form" onSubmit={assign}><label>Välj utbildning<select value={selected} onChange={(event) => setSelected(event.target.value)}>{licenses.map((license) => <option key={license.id} value={license.id}>{license.courseName}</option>)}</select></label><label>Tilldela till<select value={recipientMode} onChange={(event) => setRecipientMode(event.target.value as "existing" | "email")}><option value="existing" disabled={!recipients.length}>Befintlig medarbetare</option><option value="email">E-post / ny deltagare</option></select></label>{recipientMode === "existing" && recipients.length ? <label>Medarbetare<select required value={userId} onChange={(event) => setUserId(event.target.value)}>{recipients.map((recipient) => <option key={recipient.id} value={recipient.id}>{recipient.email}</option>)}</select></label> : <label>Deltagarens e-post<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="namn@foretag.se" /></label>}<button className="button button-dark" type="submit">Tilldela plats →</button></form><form className="license-import-form" onSubmit={importCsv}><p className="eyebrow">Massutdelning</p><label>Klistra in CSV med en e-postadress per rad<textarea required value={csv} onChange={(event) => setCsv(event.target.value)} placeholder="anna@foretag.se\njohan@foretag.se" /></label><button className="button button-light" type="submit">Tilldela deltagarlista →</button></form>{message && <p className="checkout-message" role="status">{message}</p>}</> : <p>Alla köpta platser är tilldelade.</p>}</section>;
}
