import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { createClient } from "@supabase/supabase-js";
import "./styles.css";

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL ?? "", import.meta.env.VITE_SUPABASE_ANON_KEY ?? "", { db: { schema: "kompetensportalen" }, auth: { persistSession: true, autoRefreshToken: true } });
type Course = { id: string; slug: string; name: string; short_description: string; full_description?: string; base_price_sek: number; validity_months?: number; estimated_minutes: number; status: string; tags_json?: string };

async function api(path: string, init?: RequestInit) {
  const { data: { session } } = await supabase.auth.getSession();
  const response = await supabase.functions.invoke("api", { body: { path, method: init?.method ?? "GET", body: init?.body ? JSON.parse(String(init.body)) : undefined }, headers: session ? { Authorization: `Bearer ${session.access_token}` } : undefined });
  if (response.error) throw response.error;
  return response.data;
}

function Shell({ children }: { children: React.ReactNode }) {
  return <><header className="site-header"><Link className="brand" to="/"><img className="brand-logo" src="/brand/kompetensportalen.jpg" alt="Kompetensportalen.se" /></Link><nav><Link to="/utbildningar">Utbildningar</Link><Link to="/foretag">För företag</Link><Link to="/om-oss">Om oss</Link><Link to="/kontakt">Kontakt</Link><Link to="/mina-sidor">Mina sidor</Link></nav><div className="header-actions"><Link className="header-link" to="/utbildningar">Se utbildningar →</Link><Link className="header-account" to="/login">Logga in</Link></div></header>{children}<footer><div className="footer-brand"><img className="footer-logo" src="/brand/kompetensportalen.jpg" alt="Kompetensportalen.se" /></div><p>Digital utbildning och dokumenterad kompetens för ett säkrare arbetsliv.</p><div className="footer-links"><Link to="/utbildningar">Utbildningar</Link><Link to="/foretag">Företag</Link><Link to="/kontakt">Kontakt</Link><Link to="/faq">FAQ</Link><Link to="/villkor">Köpvillkor</Link><Link to="/integritet">Integritet</Link></div><small>© 2026 WPE Sweden AB</small></footer></>;
}

function Home() { return <Shell><section className="hero"><div className="hero-copy"><p className="eyebrow">Digital kompetens för arbetslivet</p><h1>Utbildningar som gör jobbet säkrare.</h1><p className="hero-lead">Köp utbildning online, genomför den i din egen takt och få dokumenterad kompetens när du är klar.</p><div className="hero-actions"><Link className="button button-primary" to="/utbildningar">Se utbildningar →</Link><Link className="text-link" to="/foretag">För företag ↗</Link></div><div className="hero-note"><span className="status-dot" /> Svensk utbildningsplattform från WPE Sweden AB</div></div><div className="hero-visual"><div className="visual-label">KOMPETENSPORTALEN / 01</div><div className="visual-shape shape-one" /><div className="visual-shape shape-two" /><div className="visual-card"><span>APV 1.1-1.3</span><strong>Arbete på väg</strong><small>Digital utbildning · ID06</small><div className="visual-line"><i /></div><small>Certifikat efter godkänt slutprov</small></div></div></section><section className="trust-strip"><span>För bygg</span><span>För entreprenad</span><span>För industri</span><span>För transport</span><span>För infrastruktur</span></section><section className="accreditation-strip"><div className="accreditation-copy"><p className="eyebrow">Ackrediterad registrator</p><h2>Kompetens som kan registreras i ID06.</h2><p>WPE Sweden AB är ackrediterad kompetensregistrator 2026.</p></div><img src="/brand/id06-accredited-2026.jpg" alt="ID06 ackrediterad kompetensregistrator" /></section><section className="section"><div className="section-intro"><div><p className="eyebrow">Utbildningar</p><h2>Välj din utbildning</h2></div><p>Du ser kursens upplägg och villkor innan köp. Kursmaterialet öppnas först efter betald order eller tilldelad plats.</p></div><CourseGrid /></section></Shell>; }

function CourseGrid() { const [courses, setCourses] = useState<Course[]>([]); useEffect(() => { api("/courses").then((data) => setCourses(data.courses ?? [])).catch(() => setCourses([{ id: "apv", slug: "apv-1-1-3", name: "Arbete på väg – APV 1.1–1.3", short_description: "Digital APV-utbildning med examination och certifikat.", base_price_sek: 2495, estimated_minutes: 240, validity_months: 60, status: "published" }])); }, []); return <div className="course-grid">{courses.map((course, index) => <article className={`course-card ${index === 0 ? "featured" : ""}`} key={course.id}><div className="course-art"><span>{course.status === "published" ? "ONLINE" : "KOMMER SNART"}</span><b>{String(index + 1).padStart(2, "0")}</b></div><div className="course-body"><div className="course-tags"><span>{course.status === "published" ? "Online" : "Coming soon"}</span>{course.slug.includes("apv") && <span>ID06</span>}</div><h3>{course.name}</h3><p>{course.short_description}</p><div className="course-meta"><span>{course.estimated_minutes} min</span><span>{course.validity_months ? `${Math.round(course.validity_months / 12)} års giltighet` : "Varierar"}</span><strong>{course.base_price_sek.toLocaleString("sv-SE")} kr</strong></div>{course.status === "published" ? <Link className="button button-dark" to={`/utbildningar/${course.slug}`}>Läs om utbildningen →</Link> : <span className="locked-note">Kursen är inte köpbar ännu.</span>}</div></article>)}</div>; }

function Catalog() { return <Shell><section className="subpage-hero"><p className="eyebrow">Kurskatalog</p><h1>Utbildningar för ett säkrare arbetsliv.</h1><p>Välj utbildning och läs om innehåll, giltighet och certifieringskrav innan köp.</p></section><section className="section catalog-page"><CourseGrid /></section></Shell>; }
function CourseDetail() { const { slug } = useParams(); const [course, setCourse] = useState<Course | null>(null); const [message, setMessage] = useState(""); useEffect(() => { api(`/courses/${slug}`).then((data) => setCourse(data.course)).catch(() => setCourse({ id: "apv", slug: slug ?? "apv-1-1-3", name: "Arbete på väg – APV 1.1–1.3", short_description: "Digital APV-utbildning med examination och certifikat.", full_description: "Utbildningen innehåller kapitel, lektioner, quiz och slutprov.", base_price_sek: 2495, estimated_minutes: 240, validity_months: 60, status: "published" })); }, [slug]); if (!course) return <Shell><section className="section"><p>Laddar utbildning...</p></section></Shell>; return <Shell><section className="course-detail-hero"><div className="course-detail-copy"><Link className="back-link" to="/utbildningar">← Alla utbildningar</Link><p className="eyebrow">Digital utbildning · ID06</p><h1>{course.name}</h1><p>{course.short_description}</p><div className="course-detail-facts"><span><strong>{course.estimated_minutes} min</strong>Tidsåtgång</span><span><strong>{course.validity_months ? `${Math.round(course.validity_months / 12)} år` : "-"}</strong>Giltighet</span><span><strong>{course.base_price_sek.toLocaleString("sv-SE")} kr</strong>Pris exkl. moms</span></div></div><div className="purchase-card"><div className="purchase-art"><span>ID06</span><b>APV</b></div><div className="purchase-body"><div className="purchase-price"><span>Utbildning</span><strong>{course.base_price_sek.toLocaleString("sv-SE")} kr</strong></div><p>Du får tillgång efter bekräftad betalning. Tidigare genomföranden påverkas inte.</p><button className="button button-dark full-button" onClick={() => { setMessage("Köpet startas via Supabase Edge Function."); void api("/orders", { method: "POST", body: JSON.stringify({ courseId: course.id, quantity: 1 }) }); }}>Köp utbildningen →</button>{message && <small>{message}</small>}</div></div></section><section className="section detail-content"><div><p className="eyebrow">Om utbildningen</p><h2>Kunskap som följer med jobbet.</h2><p>{course.full_description ?? course.short_description}</p></div><div className="detail-list"><div><span>01</span><strong>Kursinnehåll</strong><p>Kapitel, lektioner, bilder, video och dokument.</p></div><div><span>02</span><strong>Quiz och slutprov</strong><p>Resultat och försök sparas på ditt enrollment.</p></div><div><span>03</span><strong>Certifikat</strong><p>Digitalt certifikat med verifieringskod efter godkänt resultat.</p></div></div></section></Shell>; }

function Login() { const navigate = useNavigate(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); async function submit(e: React.FormEvent) { e.preventDefault(); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) setMessage(error.message); else navigate("/mina-sidor"); } return <Shell><section className="section auth-page"><div className="auth-panel"><p className="eyebrow">Kompetensportalen.se</p><h1>Logga in</h1><form className="admin-form" onSubmit={submit}><label>E-post<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Lösenord<input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label><button className="button button-dark">Logga in</button>{message && <p className="admin-message">{message}</p>}</form></div></section></Shell>; }
function Account() { const [user, setUser] = useState<string | null>(null); const [data, setData] = useState<any>(null); useEffect(() => { supabase.auth.getUser().then(({ data }) => { setUser(data.user?.email ?? null); if (data.user) api("/enrollments").then(setData).catch(() => null); }); }, []); if (!user) return <Shell><section className="section"><h1>Logga in för att se dina utbildningar.</h1><Link className="button button-dark" to="/login">Logga in →</Link></section></Shell>; return <Shell><section className="subpage-hero"><p className="eyebrow">Mina sidor</p><h1>Din kompetens.</h1><p>{user}</p></section><section className="section"><div className="section-intro"><div><p className="eyebrow">Utbildningar</p><h2>Fortsätt där du slutade.</h2></div></div><div className="course-grid">{(data?.enrollments ?? []).map((enrollment: any) => <article className="course-card" key={enrollment.id}><div className="course-body"><p className="eyebrow">{enrollment.progress_percent ?? 0}% genomförd</p><h3>{enrollment.course_name ?? "Utbildning"}</h3><Link className="button button-dark" to={`/utbildning/${enrollment.id}`}>Öppna utbildning →</Link></div></article>)}{!data?.enrollments?.length && <p>Du har inga aktiva utbildningar ännu.</p>}</div></section></Shell>; }
function Admin() { const [data, setData] = useState<any>(null); useEffect(() => { api("/admin/dashboard").then(setData).catch(() => setData({})); }, []); return <Shell><section className="subpage-hero"><p className="eyebrow">Administration</p><h1>Kontroll på kompetensen.</h1><p>Kurser, deltagare, prov, certifikat och ID06 i ett system.</p></section><section className="section"><div className="benefit-grid"><article><span className="benefit-number">01</span><h3>{data?.courses ?? "-"}</h3><p>Kurser</p></article><article><span className="benefit-number">02</span><h3>{data?.participants ?? "-"}</h3><p>Deltagare</p></article><article><span className="benefit-number">03</span><h3>{data?.id06_pending ?? "-"}</h3><p>Väntar på ID06</p></article></div><div className="hero-actions"><Link className="button button-dark" to="/admin/kurser">Kursadministration →</Link><Link className="button button-light" to="/admin/id06">ID06-kö →</Link></div></section></Shell>; }
function AdminCourses() { const [courses, setCourses] = useState<Course[]>([]); const [message, setMessage] = useState(""); const [name, setName] = useState(""); const [slug, setSlug] = useState(""); const load = () => api("/admin/courses").then((data) => setCourses(data.courses ?? [])).catch((error) => setMessage(error.message)); useEffect(() => { void load(); }, [load]); async function create(event: React.FormEvent) { event.preventDefault(); const data = await api("/admin/courses", { method: "POST", body: JSON.stringify({ name, slug, shortDescription: "Ny utbildning", fullDescription: "Kursbeskrivning", category: "Övrigt", basePriceSek: 0, estimatedMinutes: 60 }) }); if (data.error) setMessage(data.error); else { setName(""); setSlug(""); setMessage("Kursen skapades som utkast."); load(); } } return <Shell><section className="subpage-hero"><p className="eyebrow">Administration · Kurser</p><h1>Bygg och publicera utbildningar.</h1><p>Skapa kurser, versioner och kursinnehåll. Videor och dokument lagras i Supabase Storage.</p></section><section className="section course-admin-section"><div className="course-admin-grid"><form className="admin-form" onSubmit={create}><p className="eyebrow">Ny kurs</p><h2>Skapa utkast</h2><label>Namn<input required value={name} onChange={(event) => setName(event.target.value)} /></label><label>Slug<input required value={slug} onChange={(event) => setSlug(event.target.value)} placeholder="saker-lyft" /></label><button className="button button-dark">Skapa kurs →</button>{message && <p className="admin-message">{message}</p>}</form><div className="admin-table-section"><p className="eyebrow">Kurskatalog</p><h2>{courses.length} kurser</h2><div className="admin-table">{courses.map((course) => <div className="admin-table-row" key={course.id}><div><strong>{course.name}</strong><span>{course.slug} · {course.status}</span></div><Link className="button button-light" to={`/utbildningar/${course.slug}`}>Öppna</Link></div>)}</div></div></div></section></Shell>; }
function AdminId06() { const [rows, setRows] = useState<any[]>([]); const [message, setMessage] = useState(""); useEffect(() => { api("/admin/id06").then((data) => setRows(data.registrations ?? [])).catch((error) => setMessage(error.message)); }, []); async function update(id: string, status: string) { const data = await api(`/admin/id06/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }); if (data.error) setMessage(data.error); else setRows((items) => items.map((item) => item.id === id ? data.registration : item)); } return <Shell><section className="subpage-hero"><p className="eyebrow">Administration · ID06</p><h1>Registreringar som väntar.</h1><p>Granska identitet, utbildning och registrera kompetens i ID06.</p></section><section className="section"><div className="admin-table">{rows.map((row) => <div className="admin-table-row" key={row.id}><div><strong>{row.enrollments?.courses?.name ?? row.competence_name}</strong><span>{row.status} · {row.enrollments?.users?.email ?? "-"}</span></div><button className="button button-light" onClick={() => void update(row.id, "registered")}>Markera registrerad</button></div>)}{!rows.length && <p>{message || "Inga registreringar väntar."}</p>}</div></section></Shell>; }
function CompanyPortal() { const [data, setData] = useState<any>(null); useEffect(() => { api("/company").then(setData).catch(() => setData({})); }, []); return <Shell><section className="subpage-hero company-hero"><p className="eyebrow">Företagsportal</p><h1>{data?.company?.name ?? "Kompetens för hela arbetsplatsen."}</h1><p>Hantera medarbetare, licenser och giltiga kompetenser från ett konto.</p></section><section className="section"><div className="benefit-grid"><article><span className="benefit-number">01</span><h3>{data?.members?.length ?? 0}</h3><p>Medlemmar</p></article><article><span className="benefit-number">02</span><h3>{data?.company?.organization_number ?? "-"}</h3><p>Organisationsnummer</p></article><article><span className="benefit-number">03</span><h3>CSV</h3><p>Exportera kompetensmatris</p></article></div></section></Shell>; }
function Enrollment({ exam = false }: { exam?: boolean }) { const { enrollmentId } = useParams(); const [data, setData] = useState<any>(null); const [message, setMessage] = useState(""); useEffect(() => { api(`/enrollments/${enrollmentId}`).then(setData).catch((error) => setMessage(error.message)); }, [enrollmentId]); async function complete(lessonId: string) { const result = await api("/progress", { method: "POST", body: JSON.stringify({ enrollmentId, lessonId }) }); setMessage(result.error ?? `Progress: ${result.progressPercent ?? 0}%`); } return <Shell><section className="subpage-hero"><p className="eyebrow">Kursgenomförande</p><h1>{data?.enrollment?.courses?.name ?? "Utbildning"}</h1><p>{data?.enrollment?.progress_percent ?? 0}% genomförd · Kursversion {data?.enrollment?.course_versions?.version ?? "-"}</p></section><section className="section"><div className="detail-list">{(data?.chapters ?? []).flatMap((chapter: any) => chapter.lessons ?? []).map((lesson: any) => <div key={lesson.id}><span>{lesson.type}</span><strong>{lesson.title}</strong><button className="button button-light" onClick={() => void complete(lesson.id)}>Markera klar</button></div>)}</div>{message && <p className="admin-message">{message}</p>}</section></Shell>; }
function Simple({ title, text }: { title: string; text: string }) { return <Shell><section className="subpage-hero"><p className="eyebrow">Kompetensportalen.se</p><h1>{title}</h1><p>{text}</p></section><section className="section legal-content"><h2>En plattform för dokumenterad kompetens</h2><p>Kompetensportalen samlar utbildning, examination, certifikat och företagsuppföljning. Kontakta oss om du behöver hjälp.</p></section></Shell>; }
function App() { return <Routes><Route path="/" element={<Home />} /><Route path="/utbildningar" element={<Catalog />} /><Route path="/utbildningar/:slug" element={<CourseDetail />} /><Route path="/login" element={<Login />} /><Route path="/mina-sidor" element={<Account />} /><Route path="/utbildning/:enrollmentId" element={<Enrollment />} /><Route path="/admin/kurser" element={<AdminCourses />} /><Route path="/admin/id06" element={<AdminId06 />} /><Route path="/admin/*" element={<Admin />} /><Route path="/foretag/portal" element={<CompanyPortal />} /><Route path="/foretag/*" element={<Simple title="Kompetens för hela arbetsplatsen." text="Köp platser, tilldela medarbetare och följ giltighet från ett företagskonto." />} /><Route path="/kontakt" element={<Simple title="Kontakta oss." text="Vi hjälper dig hitta rätt utbildning och komma igång." />} /><Route path="/om-oss" element={<Simple title="Ett säkrare arbetsliv börjar med rätt kompetens." text="Kompetensportalen drivs av WPE Sweden AB." />} /><Route path="*" element={<Simple title="Sidan finns inte." text="Gå tillbaka till utbildningarna." />} /></Routes>; }
createRoot(document.getElementById("root")!).render(<React.StrictMode><BrowserRouter><App /></BrowserRouter></React.StrictMode>);
