"use client";

import { useState } from "react";

type Course = { id: string; name: string };
type Rule = { id: string; courseId: string | null; minQuantity: number; maxQuantity: number | null; discountPercent: number | null; fixedUnitPriceSek: number | null; label: string; active: boolean };

export default function PriceRuleManager({ initialCourses, initialRules }: { initialCourses: Course[]; initialRules: Rule[] }) {
  const [rules, setRules] = useState(initialRules);
  const [form, setForm] = useState({ courseId: initialCourses[0]?.id ?? "", minQuantity: "3", maxQuantity: "9", mode: "percent", discountPercent: "20", fixedUnitPriceSek: "", label: "3-9 platser" });
  const [message, setMessage] = useState("");
  async function create(event: React.FormEvent) { event.preventDefault(); setMessage(""); const response = await fetch("/api/admin/price-rules", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, minQuantity: Number(form.minQuantity), maxQuantity: form.maxQuantity ? Number(form.maxQuantity) : null, discountPercent: form.mode === "percent" ? Number(form.discountPercent) : null, fixedUnitPriceSek: form.mode === "fixed" ? Number(form.fixedUnitPriceSek) : null }) }); const data = await response.json() as { rule?: Rule; error?: string }; if (!response.ok || !data.rule) return setMessage(data.error ?? "Prisregeln kunde inte skapas."); setRules((current) => [data.rule!, ...current]); setMessage("Prisregeln skapades."); }
  async function toggle(rule: Rule) { const response = await fetch("/api/admin/price-rules", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: rule.id, active: !rule.active }) }); if (response.ok) setRules((current) => current.map((item) => item.id === rule.id ? { ...item, active: !item.active } : item)); }
  return <section className="section course-admin-section"><div className="course-admin-grid"><form className="admin-form" onSubmit={create}><p className="eyebrow">Mängdrabatt</p><h2>Ny prisregel</h2><label>Utbildning<select required value={form.courseId} onChange={(event) => setForm({ ...form, courseId: event.target.value })}>{initialCourses.map((course) => <option key={course.id} value={course.id}>{course.name}</option>)}</select></label><label>Minsta antal<input type="number" min="1" required value={form.minQuantity} onChange={(event) => setForm({ ...form, minQuantity: event.target.value })} /></label><label>Högsta antal <span>valfritt</span><input type="number" min="1" value={form.maxQuantity} onChange={(event) => setForm({ ...form, maxQuantity: event.target.value })} /></label><label>Prismodell<select value={form.mode} onChange={(event) => setForm({ ...form, mode: event.target.value })}><option value="percent">Rabatt i procent</option><option value="fixed">Fast styckpris</option></select></label>{form.mode === "percent" ? <label>Rabatt (%)<input type="number" min="0" max="100" required value={form.discountPercent} onChange={(event) => setForm({ ...form, discountPercent: event.target.value })} /></label> : <label>Fast styckpris <span>SEK</span><input type="number" min="0" required value={form.fixedUnitPriceSek} onChange={(event) => setForm({ ...form, fixedUnitPriceSek: event.target.value })} /></label>}<label>Etikett<input required value={form.label} onChange={(event) => setForm({ ...form, label: event.target.value })} placeholder="20+ företagspris" /></label><button className="button button-dark" type="submit">Skapa prisregel →</button>{message && <p className="admin-message" role="status">{message}</p>}</form><div className="admin-table-section"><p className="eyebrow">Aktiva prisregler</p><div className="admin-table">{rules.map((rule) => <div className="admin-table-row" key={rule.id}><div><strong>{rule.label}</strong><span>{rule.minQuantity}–{rule.maxQuantity ?? "∞"} platser · {rule.fixedUnitPriceSek !== null ? `${rule.fixedUnitPriceSek} kr/st` : `${rule.discountPercent ?? 0}%`}</span></div><span>{rule.active ? "Aktiv" : "Avstängd"}</span><button className="button button-light" type="button" onClick={() => void toggle(rule)}>{rule.active ? "Stäng av" : "Aktivera"}</button></div>)}</div></div></div></section>;
}
